### ISSUE TITLE
default.twig in phrozn/skeleton/layouts links to Bootstrap no longer work

### ISSUE THREAD

**Issue by rylabo** [Pawka/phrozn#103]
This seems to depend on an older version of Bootstrap that isn't on any CDN, and the current links to the minified .css and the bootstrap .js in the default.twig file do not work. (404 errors)

**Comment by Pawka** [comment]
Thanks @wasabiwimp for report, I will check.

**Comment by Pawka** [comment]
Bootstrap files were added to repository. Fixed on [0.5.6](https://github.com/Pawka/phrozn/tree/0.5.6) tag.
