### ISSUE TITLE
Jekyll Style Includes?

### ISSUE THREAD

**Issue by brycefisher** [Pawka/phrozn#104]
Is there a way to add includes at compile time to a layout via front matter? In Jekyll, here's how I'd go about it:

```
{% include {{my_variable}} %}
```

More info: http://jekyllrb.com/docs/templates/#includes

**Comment by Pawka** [comment]
Hi @brycefisher 

Phrozn is using Twig template engine. Syntax to include template via variable is:

```
{% include variable_name %}
```

For example let's add predefined variable in `config.yml` file:

```
custom_template: "my_template.twig"
```

You can access `config.yml` vars with `this` prefix in layout file. Use following code to include it in layout template:

```
{% include this.custom_template %}
```

More information about Twig includes on [documentation](http://twig.sensiolabs.org/doc/tags/include.html).
