### ISSUE TITLE
Notice when calling phr update

### ISSUE THREAD

**Issue by beberlei** [Pawka/phrozn#12]
Warning: array_merge(): Argument #1 is not an array in /usr/local/php531/lib/php/Phrozn/Site/View/Base.php on line 341

Call Stack:
    0.0003     333004   1. {main}() /usr/local/php531/bin/phr:0
    0.0101     792984   2. Phrozn\Runner\CommandLine->run() /usr/local/php531/bin/phr:15
    0.1014    1435284   3. Phrozn\Runner\CommandLine->parse() /usr/local/php531/lib/php/Phrozn/Runner/CommandLine.php:98
    0.1094    1450092   4. Phrozn\Runner\CommandLine->invoke() /usr/local/php531/lib/php/Phrozn/Runner/CommandLine.php:134
    0.1113    1579724   5. call_user_func() /usr/local/php531/lib/php/Phrozn/Runner/CommandLine.php:159
    0.1113    1579724   6. Phrozn\Runner\CommandLine\Callback\Up->execute() /usr/local/php531/lib/php/Phrozn/Runner/CommandLine.php:0
    0.1113    1579724   7. Phrozn\Runner\CommandLine\Callback\Up->updateProject() /usr/local/php531/lib/php/Phrozn/Runner/CommandLine/Callback/Up.php:49
    0.1267    1766656   8. Phrozn\Site\DefaultSite->compile() /usr/local/php531/lib/php/Phrozn/Runner/CommandLine/Callback/Up.php:88
    0.1654    2632388   9. Phrozn\Site\DefaultSite->processQueue() /usr/local/php531/lib/php/Phrozn/Site/DefaultSite.php:48
    0.9029    3820460  10. Phrozn\Site\View\Base->getParam() /usr/local/php531/lib/php/Phrozn/Site/DefaultSite.php:66
    0.9032    3844820  11. Phrozn\Site\View\Base->getParams() /usr/local/php531/lib/php/Phrozn/Site/View/Base.php:315
    0.9073    3847336  12. array_merge() /usr/local/php531/lib/php/Phrozn/Site/View/Base.php:341

**Comment by farazdagi** [comment]
can you, please, confirm if it is this happening for files that do not have front matter?

**Comment by farazdagi** [comment]
https://github.com/farazdagi/phrozn/commit/c9403de62a7fbc5837353a86e8355278188fce0d should fix the issue. Hotfix released as ver. 0.2.1

**Comment by beberlei** [comment]
I changed the permalink to be more simple so this doesnt occur anymore before, sorry :)
