### ISSUE TITLE
Problems with skipping files and scripts folder

### ISSUE THREAD

**Issue by o** [Pawka/phrozn#20]
Selam Victor,

Today i discovered two different problems with Phrozn. First of all, .DS_Store files not ignoring and copied when updating project. 

Second, 
I added a empty file named README to <code>scripts</code> folder, but phrozn writes <code>.phrozn/scripts/README</code> to root folder with name README, also <code>scripts</code> **(oh sorry not styles)** folder not be created. 

Here is the screenshot about this problems http://i53.tinypic.com/iqwha1.png 
Görüşmek üzere

**Comment by farazdagi** [comment]
Selam Osman!

Will look into ignore files issue.

Regarding README file in scripts ending up in root directory - nice catch. Basically default processor doesn't know where to put README file and fallbacks to rood directory, while it should fallback in directory original source file defined (in our case <code>/scripts/</code>).

When it comes to <code>styles</code> folder not being created, can you please re-check. In image you provided, it seems styles/screen.css is created, I tested it on my box, it also seems to be created ok. Can you please confirm?

Thanks,
Kendine iyi bak,
Victor

**Comment by o** [comment]
Selam Victor, 

I updated my issue (dalgınlıkla yanlış yazmışım kusuruma bakma) when i add README file to scripts folder, README file copied to root folder and **scripts folder not be created**. And there is no problem with styles folder. 

Görüşmek üzere
Osman

**Comment by farazdagi** [comment]
Osman,
Ok I see now! Thanks for reporting, will make sure I update fallback policy - so that even non-script file defined in scripts folder, ends up in <code>scripts</code> directory on compilation.

Once again, thanks for the report!

Görüşmek üzere,
Victor

**Comment by farazdagi** [comment]
Fixed, thanks to @sumpygump PR.
