### ISSUE TITLE
Simple way to get Phrozn to recognize .md as markdown?

### ISSUE THREAD

**Issue by aaronshaf** [Pawka/phrozn#24]
Currently it only seems to recognize .markdown, not .md

Any tips?

**Comment by farazdagi** [comment]
This has been already reported (on IRC, and via email), and we definitely need this. Pushed this up in my priority list, will be available in next minor release.

**Comment by resmo** [comment]
+1

**Comment by farazdagi** [comment]
.md processor has been added (f361d8abe6de93925f28f1c25d43d2cb2ce0f9fa) to `dev` branch. Will be available with 0.5 version release.
