### ISSUE TITLE
Entry variables in layouts?

### ISSUE THREAD

**Issue by aaronshaf** [Pawka/phrozn#26]
I've set the title front layout variable in my entry, but neither {{ title }} nor {{ this.title }} seems to work in the default.twig layout. Any ideas?

**Comment by farazdagi** [comment]
<code>{{ this.title }}</code> works both for FM in entries and in layout. Just tested with phr 0.3.2

**Comment by aaronshaf** [comment]
I'm on 0.3.2 and I'm unfortunately not getting the same result. Here is my entry, layout, and rendered result:

https://gist.github.com/1369484

**Comment by aaronshaf** [comment]
I tried "phr update", as well as clearing out public_html and re-running "phr up"

**Comment by farazdagi** [comment]
Variables are scoped. You define var in entry, it is available in entry (and not available in layout). You may define <code>title</code> in layout, it will be available in layout, not in entries.

Twig has blocks for achieving what you are trying to do - you define <code>{% block title %} in layout {% endblock %}</code> and then redefine it in your entries.

You can find more examples in unit tests - https://github.com/farazdagi/phrozn/blob/master/tests/Phrozn/Site/project/.phrozn/entries/twig-child-with-fm.twig

**Comment by aaronshaf** [comment]
Let me put it this way: Is there a way to customize the title in the layout using the variable set in the FM of the entry?

I'd like to use Markdown in my entries anyway, so block seem out of the question?

**Comment by farazdagi** [comment]
You have a point here - I will look into passing entry front-matter into layout.

Thanks for pushing the issue forward - it is easy to implement, and features real use case.

For time being, please, continue w/o modifying the layout, and I will make sure that this request ends up in next minor release as well.

**Comment by aaronshaf** [comment]
Perhaps this patch already fixed the problem?

https://github.com/farazdagi/phrozn/pull/21

**Comment by aaronshaf** [comment]
Yup, that patch does the trick, letting me use {{entry.title}} in the layout

**Comment by farazdagi** [comment]
Seems I manage too many projects at the same time. Merged the thing just couple of weeks ago. Let me release it as a minor version immediately - so that everybody who spots this discussion can use it from master branch.

**Comment by aaronshaf** [comment]
Thanks much!
