### ISSUE TITLE
Phrozn/Autoloader.php

### ISSUE THREAD

**Issue by jeanmichelcote** [Pawka/phrozn#39]
Trying installing Phrozn on a dreamhost shared account and here is the message from the terminal:

Warning: require_once(Phrozn/Autoloader.php): failed to open stream: No such file or directory in /home/myuser/pear/phr on line 12

Fatal error: require_once(): Failed opening required 'Phrozn/Autoloader.php' (include_path='.:/usr/local/lib/php:/usr/local/php5/lib/pear') in /home/myuser/pear/phr on line 12

I'm quite new to this so if anyone got an idea, you're more than welcome...

**Comment by farazdagi** [comment]
- I guess it is known issue #19 
- will need to look into it as it has been sitting in todo list for ever
