### ISSUE TITLE
No releases available

### ISSUE THREAD

**Issue by benjaminach** [Pawka/phrozn#46]
Hello,

When i want to install the beta package i have an error :

```
C:\PHP>pear install phrozn/Phrozn-beta
No releases available for package "pear.phrozn.info/Phrozn"
install failed


C:\PHP>pear remote-list -c phrozn
CHANNEL PHROZN AVAILABLE PACKAGES:
==================================
PACKAGE VERSION
Phrozn  -n/a-
```

Is there a problem with my installation or you repository ?

**Comment by farazdagi** [comment]
Just tried it - repository works ok and I was able to install on my Mac box.
Another issue you might encounter is that I never tested Phrozn on Wins, so phrozn's support of this platform is limited (it is probably unrelated to current issue, but even if you'd be able to install,  phr performance is untested).

**Comment by benjaminach** [comment]
Ok,

I have fix my issue.

Clear the temp/cache folder of pear in C:\Users\USER\AppData\Local\Temp\pear
