### ISSUE TITLE
Unittest failed

### ISSUE THREAD

**Issue by bladeofsteel** [Pawka/phrozn#51]
"Out of the box" test fails. Need instructions for setup the environment for the unittests.

**Comment by Grummfy** [comment]
On dev branch :

I read travis to have some clue about this
- you need pear with pear/Console_CommandLine, pear/Console_Color2-alpha, pear/PHP_CodeSniffer
- run following commands
  - PATH=$PATH:$(pwd) ; export PATH ; ln -s $(pwd)/bin/phr.php $(pwd)/phr-dev
  - phpunit --configuration tests/phpunit.xml

But even after that phpunit failed with

> Configuration read from /phrozn/tests/phpunit.xml
> 
> Time: 0 seconds, Memory: 9.25Mb
> 
> There was 1 error:
> 
> 1) PhroznTest\Bundle\DefaultSiteTest::testListNoParams
> PHPUnit_Framework_Exception: PHP Fatal error:  Call to undefined method Symfony\Component> \Yaml\Yaml::load() in /phrozn/Phrozn/Config.php on line 58
> PHP Stack trace:
> PHP   1. {main}() -:0
> PHP   2. __phpunit_run_isolated_test() -:184
> PHP   3. PHPUnit_Framework_TestCase->run() -:26
> PHP   4. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:769
> PHP   5. PHP_Invoker->invoke() /usr/share/php/PHPUnit/Framework/TestResult.php:646
> PHP   6. call_user_func_array() /usr/share/php/PHP/Invoker.php:93
> PHP   7. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHP/Invoker.php:93
> PHP   8. PhroznTest\Bundle\DefaultSiteTest->setUp() /usr/share/php/PHPUnit/Framework/TestCase.php:821
> PHP   9. Phrozn\Config->__construct() /phrozn/tests/Phrozn/Bundle/ServiceTest.php:45

**Comment by Grummfy** [comment]
I found some clue to resolve this mainly is version of lib that have deprecated call or code that have been refactored in these libs
I will try to solve this : https://github.com/Grummfy/phrozn/tree/fixPhpUnitTest

**Comment by farazdagi** [comment]
Jonathan, it will be really good if you can fix those issues.

**Comment by Grummfy** [comment]
Here is my fix : https://github.com/farazdagi/phrozn/pull/57
I think it's better than you fix the failure test (I don't know why they don't work so ...)

**Comment by bladeofsteel** [comment]
@Grummfy I try your branch and still got many failed tests

PHPUnit 3.7.1 / Php 5.3.10

**Comment by Grummfy** [comment]
I have 16 failure,
But perhaps you should list the pear package version you have installed....

**Comment by bladeofsteel** [comment]
Here is:

# Installed packages, channel __uri:

(no packages installed)

# Installed packages, channel components.ez.no:

Package      Version State
Base         1.8     stable
ConsoleTools 1.6.1   stable

# Installed packages, channel dist.photon-project.com:

Package Version State
photon  0.2.0   beta

# Installed packages, channel doc.php.net:

(no packages installed)

# Installed packages, channel pear.pdepend.org:

Package    Version State
PHP_Depend 1.0.4   stable

# Installed packages, channel pear.php.net:

Package             Version State
Archive_Tar         1.3.9   stable
Console_Color       1.0.3   stable
Console_Color2      0.1.1   alpha
Console_CommandLine 1.1.3   stable
Console_Getopt      1.3.1   stable
Console_Table       1.1.4   stable
Log                 1.12.7  stable
PEAR                1.9.4   stable
PHPUnit             1.3.2   stable
PHP_CodeSniffer     1.3.6   stable
PhpDocumentor       1.4.4   stable
Structures_Graph    1.0.4   stable
XML_Util            1.2.1   stable

# Installed packages, channel pear.phpmd.org:

Package Version State
PHP_PMD 1.3.3   stable

# Installed packages, channel pear.phpqatools.org:

Package    Version State
phpqatools 1.0.0   stable

# Installed packages, channel pear.phpundercontrol.org:

(no packages installed)

# Installed packages, channel pear.phpunit.de:

Package                   Version State
DbUnit                    1.1.2   stable
File_Iterator             1.3.1   stable
PHPUnit                   3.7.1   stable
PHPUnit_MockObject        1.2.0   stable
PHPUnit_Selenium          1.2.5   stable
PHPUnit_SkeletonGenerator 1.1.0   stable
PHP_CodeBrowser           1.0.2   stable
PHP_CodeCoverage          1.2.1   stable
PHP_Invoker               1.1.0   stable
PHP_Timer                 1.0.2   stable
PHP_TokenStream           1.1.3   stable
Text_Template             1.1.1   beta
phpcpd                    1.3.5   stable
phploc                    1.6.4   stable

# Installed packages, channel pear.phrozn.info:

(no packages installed)

# Installed packages, channel pear.symfony-project.com:

Package Version State
YAML    1.0.6   stable

# Installed packages, channel pear.symfony.com:

Package Version State
Yaml    2.1.2   stable

# Installed packages, channel pear.zero.mq:

Package Version State
zmq     1.0.3   beta

# Installed packages, channel pecl.php.net:

Package   Version State
gearman   1.0.2   stable
mongo     1.2.9   stable
pecl_http 1.7.3   stable

**Comment by farazdagi** [comment]
Hi guys!
@Grummfy I will look into #57 and review the rest of failing cases. Thanks for the pull request!

**Comment by farazdagi** [comment]
@bladeofsteel @Grummfy should be fixed now: https://travis-ci.org/farazdagi/phrozn

**Comment by bladeofsteel** [comment]
I still got error :(

```
PHPUnit 3.7.13 by Sebastian Bergmann.

Configuration read from /home/oleg/projects/self/phrozn/tests/phpunit.xml

..............................E

Time: 01:09, Memory: 11.50Mb

There was 1 error:

1) PhroznTest\Outputter\DefaultOutputterTest::testStdOutWithResource
fwrite(): 95 is not a valid stream resource

/home/oleg/projects/self/phrozn/Phrozn/Outputter/DefaultOutputter.php:46
/home/oleg/projects/self/phrozn/tests/Phrozn/Outputter/DefaultOutputterTest.php:61

FAILURES!
Tests: 31, Assertions: 142, Errors: 1.

Generating code coverage report in HTML format ... done
```

**Comment by farazdagi** [comment]
What version of PHP you are on? PHP 5.4 will fail with this error. PHP 5.3 should work ok.

**Comment by bladeofsteel** [comment]
Yes, I test on 5.4.
Do you know how to fix this?

**Comment by farazdagi** [comment]
Switch to PHP 5.3? :))

If srsly, I will look into Outputtter issue, but this is not a priority (does bin/phr.php work? I suppose it should as Outputter was written for UTs, it should prevent main utility to work).

**Comment by bladeofsteel** [comment]
> Switch to PHP 5.3? :))

LOL

> does bin/phr.php work?

I`ll check it today

**Comment by wdalmut** [comment]
Take a look the pull #65 I have also fixed tests on Outputter for PHP 5.3

**Comment by farazdagi** [comment]
@wdalmut Aha, I see (suppose you refer to 47800f79cf3afff33990dd31a99f8e7bba882939). Great, will now work on reviewing and merging it, and then add PHP 5.4 to travis.yml so that we have that version covered too.

Good work btw on `phr single`!

**Comment by farazdagi** [comment]
@bladeofsteel PHP 5.4 should not be problem anymore (thanks to @wdalmut).

Travis-CI tests: https://travis-ci.org/farazdagi/phrozn/jobs/4246725

**Comment by bladeofsteel** [comment]
> @bladeofsteel PHP 5.4 should not be problem anymore (thanks to @wdalmut).

it is, confirm

time to make phrozn engine for the blog? ;)

**Comment by farazdagi** [comment]
@bladeofsteel yep, need to tackle the #14 now
