### ISSUE TITLE
Switch to Composer

### ISSUE THREAD

**Issue by Pawka** [Pawka/phrozn#59]
# Problem
- Vendors code should not be stored on repository.
- Console_CommandLine and Console_Color2 are not included to Vendors and must be installed globally on the system.
# Suggestion
- Prepare Phrozn to be installed via Composer (we'll switch to Composer autoloader instead of current one).
- Composer will download all dependencies and Vendors code will be removed from source.
- Phrozn will run independently from global libraries.

What do you think about my suggestion? If you need help, I can work on this.

**Comment by farazdagi** [comment]
Povilas, yep agree with a problem statement and proposed resolution. If you have time, feel free to take care of implementation, and I will merge on pull request.

**Comment by Pawka** [comment]
Ok. I'm working on this.

**Comment by farazdagi** [comment]
Povilas, great work! Reviewing your pull request, will merge today.

**Comment by farazdagi** [comment]
done: 259a069
