### ISSUE TITLE
PEAR_Exception Class Not found

### ISSUE THREAD

**Issue by farrelley** [Pawka/phrozn#68]
The PEAR_Exception class is not found.  It need to be added to the composer file somehow.  It's extended through Console_CommandLine_Exception  

PEAR_Exception GitHub repo is https://github.com/pear/PEAR_Exception/

Will issue PR if I can figure out how to get this in.

**Comment by farazdagi** [comment]
Yep, indeed. Will also meditate on what is the best way to include it :) 

PR is always welcome!

**Comment by farrelley** [comment]
One way is to just get Exception stuff from github with package type zip.

``` javascript
{
            "type": "package",
            "package": {
                "name": "pear/Pear_Exception",
                "version": "dev-master",
                "dist": {
                    "url": "https://github.com/pear/PEAR_Exception/archive/master.zip",
                    "type": "zip"
                }
            }
        }
```

then Include require:

``` javascript
"pear/Pear_Exception": "dev-master"
```

All it needs to do is to be autoloaded correctly.

**Comment by farazdagi** [comment]
Seems quite a good solution to me. Pls, feel free to file the pull request.

**Comment by Pawka** [comment]
It is Console_CommandLine bug. I'm currently fixing phrozn-related pear repositories and it will be enough just to have Console_CommandLine in Phrozn/composer.json. Not sure how long it will take until they'll accept all my PRs.

@farazdagi This would be temporary fix. I would suggest to wait until PEAR repos will be fixed and do not include this PR.

**Comment by farrelley** [comment]
@Pawka That's probably the best way to fix this.

**Comment by farazdagi** [comment]
@Pawka @farrelley Agreed, let's wait and see when PEAR component is fixed.

**Comment by fgrehm** [comment]
hey @farrelley, would you mind pasting your composer.json down here?  wasn't able to get it working
I really wanted to try out phrozn but it's been I while since I last used PHP and composer is brand new to me :p

tks!

**Comment by farrelley** [comment]
@fgrehm - https://github.com/farazdagi/phrozn/issues/68#issuecomment-12500681  I just added that.  Just need to add in the autoloading to psr-0 section.  That's the work around.

**Comment by fgrehm** [comment]
@farralley tks for the answer but I wasn't able to get it working
here's what I tried:
  https://gist.github.com/8f7c995b344a339dc250

**Comment by Pawka** [comment]
@fgrehm Add `"pear/Pear_Exception": "dev-master"` part to `required` instead of `autoload`.
