### ISSUE TITLE
Support for Scss

### ISSUE THREAD

**Issue by mikehaas763** [Pawka/phrozn#79]
Phrozn currently uses leafo's phpless compiler. They also have a very similar Scss compiler. It should be pretty trivial to add support for it.

**Comment by farazdagi** [comment]
Thanks, me or other contributors will definitely look into that at some point. 

If you want this to be included sooner though, please, go ahead and provide some code via pull request - will make sure I review and merge it promptly.

**Comment by mikehaas763** [comment]
I'm actually working on that right now :)

**Comment by mikehaas763** [comment]
This has been added: see #80

**Comment by Pawka** [comment]
@farazdagi This issue should be closed already.
